### ISSUE TITLE
Extension to RGB Point cloud

### ISSUE THREAD

**Issue by MichaelFYang** [fzi-forschungszentrum-informatik/vdb_mapping_ros#3]
Hi,

This issue is more of a discussion to extend the current pipeline to process the RGB point cloud. The current mechanism is to capture a voxel's occupancy, and changing the OpenVDB grid with a custom data structure is not trivial. Is there any further work of you guys on this problem, or if you have an idea that we can do it easily (maybe I have overthought this problem)? I can also help on this end.

Best,

**Comment by MGBla** [comment]
Hey Michael,

there is actually a development branch in our local repository, which provides custom data types in the map. However, it is currently in a rather rough state, with respect to the insert interfaces. Also we are planning to restructure it a lot in the future. Nevertheless, if you're interested I can probably push the branch also here.

**Comment by MichaelFYang** [comment]
That will be very helpful. And if it is okay, I can also help with the development. Having custom data types will be nice.

**Comment by MichaelFYang** [comment]
Hi Marvin,

I just wanted to follow up on this issue, have you pushed the branch yet?

**Comment by MGBla** [comment]
Hey Michael,
sorry I still have to clean up a little bit in there and didn't had the time to do it. But hope i will get it done in the next few days

**Comment by MichaelFYang** [comment]
Hi Marvin, thanks a lot.

**Comment by MGBla** [comment]
Hey Fan,

sorry still not happy with the current version. Also we are planning to completely restructure it into a layered approach in the near future. Since I didn't want to clutter this repo is pushed the current version of the custom data stuff on my private fork:
https://github.com/MGBla/vdb_mapping
https://github.com/MGBla/vdb_mapping_ros

However, this part is highly experimental and not that easily usable and will be removed/exchanged for a nicer approach with better interfacing hopefully soon-ish
